# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the action will run.
on:
  # Triggers the workflow on push and pull request events
  push:
    branches: [ master ]
  pull_request:
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin  

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install

      - name: Build Page
        run: npm run build

      - name: Build the docker-compose stack  
        run: docker build . -t ghcr.io/projectblacktube/blacktube-website:latest

      - name: Push images
        run: docker push ghcr.io/projectblacktube/blacktube-website:latest
